workspace = name:TV, monitor:HDMI-A-2, persistent:true

plugin {
    split-monitor-workspaces {
        count = 10
        monitor_priority = DP-3, DP-2, HDMI-A-2
        keep_focused = 0
        enable_notifications = 0
        enable_persistent_workspaces = 0
        enable_wrapping = 1
    }
}
